### ISSUE TITLE
pootle initdb troubles

### ISSUE THREAD

**Issue by Olegt0rr** [1drop/pootle#12]
**Step by step:**
`docker-compose up -d` - success
`docker-compose exec pootle bash` - success
`pootle migrate` - success

and then:
```
root@4e09e93abf25:/home/pootle# pootle initdb
2019-06-08 12:12:02,516 INFO Loading custom settings from '/root/.pootle/pootle.conf'...
2019-06-08 12:12:02,812 INFO Using Python PO
Populating the database.
Traceback (most recent call last):
  File "/usr/local/bin/pootle", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 319, in main
    django_settings_module='pootle.settings')
  File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 299, in run_app
    management.execute_from_command_line(command)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/management/commands/initdb.py", line 36, in handle_noargs
    initdb(options["create_projects"])
  File "/usr/local/lib/python2.7/dist-packages/pootle/core/initdb.py", line 33, in initdb
    create_revision()
  File "/usr/local/lib/python2.7/dist-packages/pootle/core/initdb.py", line 76, in create_revision
    Revision.initialize()
  File "/usr/local/lib/python2.7/dist-packages/pootle/core/models.py", line 35, in initialize
    return cls.add(cls.INITIAL)
  File "/usr/local/lib/python2.7/dist-packages/pootle/core/models.py", line 62, in add
    return cache.add(cls.CACHE_KEY, value)
  File "/usr/local/lib/python2.7/dist-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_redis/cache.py", line 75, in add
    return self.client.add(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_redis/client/default.py", line 190, in add
    return self.set(key, value, timeout, version=version, client=client, nx=True)
  File "/usr/local/lib/python2.7/dist-packages/django_redis/client/default.py", line 148, in set
    return client.set(nkey, nvalue, nx=nx, ex=timeout, xx=xx)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 774, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 663, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 125, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
```

**Comment by ghost** [comment]
> **Step by step:**
> `docker-compose up -d` - success
> `docker-compose exec pootle bash` - success
> `pootle migrate` - success
> 
> and then:
> 
> ```
> root@4e09e93abf25:/home/pootle# pootle initdb
> 2019-06-08 12:12:02,516 INFO Loading custom settings from '/root/.pootle/pootle.conf'...
> 2019-06-08 12:12:02,812 INFO Using Python PO
> Populating the database.
> Traceback (most recent call last):
>   File "/usr/local/bin/pootle", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 319, in main
>     django_settings_module='pootle.settings')
>   File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 299, in run_app
>     management.execute_from_command_line(command)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
>     self.execute(*args, **options.__dict__)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
>     return self.handle_noargs(**options)
>   File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/management/commands/initdb.py", line 36, in handle_noargs
>     initdb(options["create_projects"])
>   File "/usr/local/lib/python2.7/dist-packages/pootle/core/initdb.py", line 33, in initdb
>     create_revision()
>   File "/usr/local/lib/python2.7/dist-packages/pootle/core/initdb.py", line 76, in create_revision
>     Revision.initialize()
>   File "/usr/local/lib/python2.7/dist-packages/pootle/core/models.py", line 35, in initialize
>     return cls.add(cls.INITIAL)
>   File "/usr/local/lib/python2.7/dist-packages/pootle/core/models.py", line 62, in add
>     return cache.add(cls.CACHE_KEY, value)
>   File "/usr/local/lib/python2.7/dist-packages/django_redis/cache.py", line 32, in _decorator
>     return method(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/django_redis/cache.py", line 75, in add
>     return self.client.add(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/django_redis/client/default.py", line 190, in add
>     return self.set(key, value, timeout, version=version, client=client, nx=True)
>   File "/usr/local/lib/python2.7/dist-packages/django_redis/client/default.py", line 148, in set
>     return client.set(nkey, nvalue, nx=nx, ex=timeout, xx=xx)
>   File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1451, in set
>     return self.execute_command('SET', *pieces)
>   File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 774, in execute_command
>     connection.send_command(*args)
>   File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 620, in send_command
>     self.send_packed_command(self.pack_command(*args))
>   File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 663, in pack_command
>     for arg in imap(self.encoder.encode, args):
>   File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 125, in encode
>     "byte, string or number first." % typename)
> redis.exceptions.DataError: Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
> ```

Me too.
Can you fix it?

**Comment by arky** [comment]
Perhaps related to https://github.com/translate/pootle/issues/6887
